name: JMeter Performance Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Download and Setup JMeter
      run: |
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.2.tgz
        tar -xzf apache-jmeter-5.6.2.tgz
        echo "JMETER_HOME=$GITHUB_WORKSPACE/apache-jmeter-5.6.2" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/apache-jmeter-5.6.2/bin" >> $GITHUB_PATH
    
    - name: Run JMeter Test
      run: |
        mkdir -p reports
        jmeter -n -t test-plan/users-test-plan.jmx \
               -l results.jtl \
               -e -o reports
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: jmeter-test-results
        path: |
          results.jtl
          reports/ 